"""Public research API for Q-GapSelect.

The package exposes analytic and exact-state reference backends alongside
separately labelled candidate-complexity accounting.  Exact-state execution is
still a classical simulation, and importing a ``candidate_*`` symbol must not
be interpreted as importing a proved quantum bound.
"""

from .activity_history_transducer import (
    ActivityHistoryResources,
    ActivityHistoryResult,
    ToyActivityHistoryTransducer,
    toy_transducer_from_history_record,
)
from .adaptive_phase import (
    AdaptivePhaseQubitScheduler,
    AdaptivePhaseSchedule,
    PhaseQubitCandidate,
)
from .attack_metrics import AttackMetrics, aggregate_attack_metrics
from .attack_oracles import (
    BlindSourceRewardOracle,
    CandidateEdge,
    FrozenCandidateGraph,
    FrozenSourceFixture,
    SourceOracleBudget,
    generate_bernoulli_landscape,
)
from .attack_selectors import (
    CostAwareRacingSelector,
    GCGSGreedyGraphSelector,
    InternalCLUCBStyleSelector,
    RandomSelector,
    SuccessiveHalvingSelector,
    UniformTopKSelector,
)
from .ccfa_evidence_gate import (
    CCFAEvidenceGateConfig,
    CCFAEvidenceGateReport,
    PreregisteredFixture,
    evaluate_ccfa_evidence_gate,
)
from .ccfa_matched_benchmarking import (
    AtomicQueryCapOracle,
    CCFAMatchedAggregate,
    CCFAMatchedBenchmarkConfig,
    CCFAMatchedTrialRecord,
    aggregate_ccfa_matched_trials,
    iter_ccfa_matched_trials,
    matched_campaign_manifest_hash,
    validate_complete_matched_panel,
)
from .charged_activity_history import (
    ChargedActivityResources,
    ChargedActivityResult,
    ChargedActivitySummary,
    ChargedPhaseHistoryTransducer,
    FinitePhaseClassification,
    deterministic_boundary_phases,
    logarithmic_precision_schedule,
)
from .coherent import CanonicalRyStatevectorOracle
from .coherent_activity_history_core import (
    CandidateCircuitIRResources,
    ExecutedHistoryResources,
    FreshVerificationRecord,
    HistoryBranchRegister,
    HistoryIRInstruction,
    HistoryIROp,
    HistoryLayerExecution,
    HistoryOutput,
    StrictTopKHistoryCertificate,
    VariableTimeCoherentActivityHistoryCore,
    VariableTimeCoherentHistoryResult,
    VariableTimeHistoryConfig,
    run_variable_time_coherent_activity_history,
)
from .coherent_activity_history_statevector import (
    CoherentActivityHistoryStatevectorKernel,
    CoherentHistoryStatevectorConfig,
    CoherentHistoryStatevectorResources,
    CoherentHistoryStatevectorResult,
    MeasuredBoundaryBracket,
    run_coherent_activity_history_statevector,
)
from .composition_audit import (
    CompositionAuditRecord,
    composition_audit_sweep,
    composition_loglog_slope,
    orientation_family_composition_record,
)
from .composition_frontier import (
    CompositionBaseline,
    CompositionFrontierRecord,
    composition_frontier_loglog_slope,
    composition_frontier_record,
    composition_frontier_sweep,
)
from .contracts import CoherentOracleContract, CoherentRewardGate, OracleModel
from .direct_baselines import ClassicalThresholdScan, IndependentQPEThresholdScan
from .direct_phase import (
    DirectAmplitudeThresholdFlag,
    DirectPhaseFlagResources,
    DirectPhaseFlagResult,
    DirectPhaseThresholdFlag,
    IndexVerificationResult,
)
from .direct_search import (
    DirectSearchAttempt,
    DirectSearchResources,
    DirectThresholdSearchResult,
    FullWorkspaceBBHT,
    full_workspace_rank_one_diffusion,
)
from .direct_topk import (
    CalibratedDirectTopKController,
    CalibratedDirectTopKResult,
    DirectTopKBranchTrace,
    DirectTopKResources,
)
from .estimators import AnalyticIterativeAmplitudeEstimator, IterativeAmplitudeEstimator
from .exact_count_fixtures import generate_exact_count_fixture
from .fixed_fixture_calibration import (
    AnchorSelectionRecord,
    FixedFixtureCalibrationReport,
    one_sided_clopper_pearson_lower,
    select_hardness_quantile_anchors,
    summarize_fixed_fixture_calibration,
)
from .frozen_coherent_oracle import (
    FrozenCoherentOracleDescriptor,
    FrozenCoherentOracleProtocol,
    FrozenEmpiricalCoherentOracle,
    build_frozen_empirical_coherent_oracle,
)
from .frozen_paired_statistics import (
    FrozenPairedAnalysis,
    FrozenQuantumPairedAdapterResult,
    PairedFixtureOutcome,
    analyze_frozen_quantum_reference_pairs,
    analyze_paired_fixtures,
    holm_fwer_adjusted_p_values,
)
from .frozen_quantum_instance_design import (
    AngularGapStructureDescriptor,
    FrozenQuantumInstanceDesign,
    generate_frozen_quantum_instance_design,
)
from .frozen_quantum_reference_benchmarking import (
    INDEPENDENT_IAE_INFORMATION_REGIME,
    KNOWN_THRESHOLD_IAE_INFORMATION_REGIME,
    QGAPSELECT_INFORMATION_REGIME,
    FrozenQuantumMethodConfigs,
    FrozenQuantumReferenceBenchmarkReport,
    FrozenQuantumReferenceInstance,
    run_frozen_quantum_reference_benchmark,
)
from .frozen_selector_benchmarking import (
    FrozenSelectorBenchmarkReport,
    SelectorBenchmarkAggregate,
    SelectorBenchmarkRun,
    SelectorBudget,
    SelectorLandscape,
    run_frozen_selector_benchmark,
)
from .gapselect import QGapSelect
from .independent_iae_topk import (
    IndependentIAETopKReference,
    IndependentIAETopKResult,
    run_independent_iae_topk,
)
from .iterative_ae_baseline import IterativeAEThresholdScan
from .llm_attack import (
    AttackStudyPlan,
    CallableGenerationValidator,
    CallableLocalModelAdapter,
    CounterfactualRateSelector,
    EvaluatedGeneration,
    GenerationRecord,
    GenerationRequest,
    OfflineReplayBackend,
    QGapSelectPortfolioAdapter,
    QueryBudget,
    Seed,
    SemanticVariant,
    Task,
    ValidatorResult,
    collect_local_records,
    paired_counterfactual_event,
    run_attack_study,
)
from .lower_bound_program import (
    LowerBoundBlock,
    LowerBoundProgramRecord,
    lower_bound_program_loglog_slope,
    lower_bound_program_record,
    lower_bound_program_sweep,
)
from .models import GapSelectConfig, GapSelectResult, IAEConfig, TopKInstance
from .natural_oracles import (
    NaturalArmDistribution,
    NaturalPurificationStatevectorOracle,
)
from .oracles import CanonicalBernoulliOracleSimulator, QueryKind, QueryLedger
from .primitives import (
    DovetailTopKController,
    QBoundaryEstimator,
    QGapFlag,
    qbatch_extract,
    qboundary,
    qgap_flag,
)
from .proof_ledger import (
    ProofLedger,
    ProofLedgerEntry,
    build_proof_ledger,
    proof_ledger_markdown,
)
from .quantum_benchmarking import (
    QuantumBenchmarkConfig,
    QuantumBenchmarkRunner,
    aggregate_benchmark_records,
    make_benchmark_instance,
    paired_query_ratios,
)
from .quantum_diagnostics import (
    run_diffusion_ablation,
    run_phase_grid_sweep,
    run_qpe_acceptance_sweep,
)
from .quantum_validation import run_unitary_validation, run_verifier_calibration
from .research_gap_audit import (
    ArtifactEvidence,
    ResearchGap,
    ResearchGapAudit,
    build_research_gap_audit,
    research_gap_markdown,
    summarize_charged_activity,
    summarize_composition_frontier,
    summarize_lower_bound_program,
    summarize_proof_ledger,
    summarize_quantum_benchmark,
    summarize_stopping_transducer,
    summarize_stopping_unitary_theorem,
    summarize_unknown_boundary_grid,
    summarize_variable_time_charged,
)
from .stopping_time_theorem import (
    LemmaCheck,
    StoppingUnitaryLemmaScaffold,
    build_stopping_unitary_lemma_scaffold,
    stopping_unitary_lemma_markdown,
)
from .stopping_time_transducer import (
    StoppingProfile,
    StoppingResources,
    StoppingResult,
    StoppingSummary,
    VariableTimeStoppingTransducer,
    precision_bits_from_history_record,
)
from .theorem_closure_audit import (
    ComplexityInstantiation,
    TheoremObligation,
    UnifiedHardFamily,
    UnifiedQueryInterface,
    UnifiedTheoremClosureAudit,
    build_unified_theorem_closure_audit,
    machine_readable_status_map,
)
from .theory_falsification import (
    OrientationSeparationRecord,
    descriptive_loglog_slope,
    orientation_separation_record,
    orientation_separation_sweep,
)
from .uci_classifier_benchmarks import (
    COVERTYPE_SPEC,
    LETTER_SPEC,
    OPTDIGITS_SPEC,
    BoundaryFailure,
    ClassifierConfig,
    LoadedUCIDataset,
    UCIClassifierBenchmark,
    build_uci_classifier_benchmark,
    load_covertype,
    load_letter_recognition,
    load_optdigits,
    load_sklearn_digits_offline,
)
from .unknown_boundary_history import (
    HistoryScale,
    UnknownBoundaryHistoryRecord,
    unknown_boundary_history_loglog_slope,
    unknown_boundary_history_record,
    unknown_boundary_history_sweep,
)
from .variable_time_charged_history import (
    VariableTimeChargedHistoryRecord,
    VariableTimeChargedLevel,
    precision_bits_for_epsilon,
    variable_time_charged_history_loglog_slope,
    variable_time_charged_history_record,
    variable_time_charged_history_sweep,
)

__all__ = [
    "AdaptivePhaseQubitScheduler",
    "AdaptivePhaseSchedule",
    "ActivityHistoryResources",
    "ActivityHistoryResult",
    "AnalyticIterativeAmplitudeEstimator",
    "AngularGapStructureDescriptor",
    "ArtifactEvidence",
    "AnchorSelectionRecord",
    "AttackMetrics",
    "AttackStudyPlan",
    "BlindSourceRewardOracle",
    "BoundaryFailure",
    "CCFAEvidenceGateConfig",
    "CCFAEvidenceGateReport",
    "CCFAMatchedAggregate",
    "CCFAMatchedBenchmarkConfig",
    "CCFAMatchedTrialRecord",
    "COVERTYPE_SPEC",
    "CandidateEdge",
    "CallableGenerationValidator",
    "CallableLocalModelAdapter",
    "CandidateCircuitIRResources",
    "CanonicalBernoulliOracleSimulator",
    "CanonicalRyStatevectorOracle",
    "CalibratedDirectTopKController",
    "CalibratedDirectTopKResult",
    "ChargedActivityResources",
    "ChargedActivityResult",
    "ChargedActivitySummary",
    "ChargedPhaseHistoryTransducer",
    "ClassifierConfig",
    "ClassicalThresholdScan",
    "CoherentOracleContract",
    "CoherentRewardGate",
    "CoherentActivityHistoryStatevectorKernel",
    "CoherentHistoryStatevectorConfig",
    "CoherentHistoryStatevectorResources",
    "CoherentHistoryStatevectorResult",
    "CompositionAuditRecord",
    "CompositionBaseline",
    "CompositionFrontierRecord",
    "ComplexityInstantiation",
    "CounterfactualRateSelector",
    "CostAwareRacingSelector",
    "DirectAmplitudeThresholdFlag",
    "DirectPhaseFlagResources",
    "DirectPhaseFlagResult",
    "DirectPhaseThresholdFlag",
    "DirectSearchAttempt",
    "DirectSearchResources",
    "DirectThresholdSearchResult",
    "DirectTopKBranchTrace",
    "DirectTopKResources",
    "DovetailTopKController",
    "EvaluatedGeneration",
    "ExecutedHistoryResources",
    "FinitePhaseClassification",
    "FixedFixtureCalibrationReport",
    "FreshVerificationRecord",
    "FrozenCandidateGraph",
    "FrozenCoherentOracleDescriptor",
    "FrozenCoherentOracleProtocol",
    "FrozenEmpiricalCoherentOracle",
    "FrozenQuantumInstanceDesign",
    "FrozenPairedAnalysis",
    "FrozenQuantumMethodConfigs",
    "FrozenQuantumPairedAdapterResult",
    "FrozenQuantumReferenceBenchmarkReport",
    "FrozenQuantumReferenceInstance",
    "FrozenSelectorBenchmarkReport",
    "FrozenSourceFixture",
    "GapSelectConfig",
    "GapSelectResult",
    "IAEConfig",
    "INDEPENDENT_IAE_INFORMATION_REGIME",
    "IterativeAmplitudeEstimator",
    "KNOWN_THRESHOLD_IAE_INFORMATION_REGIME",
    "PairedFixtureOutcome",
    "GenerationRecord",
    "GenerationRequest",
    "FullWorkspaceBBHT",
    "HistoryScale",
    "HistoryBranchRegister",
    "HistoryIRInstruction",
    "HistoryIROp",
    "HistoryLayerExecution",
    "HistoryOutput",
    "IndexVerificationResult",
    "IndependentQPEThresholdScan",
    "IndependentIAETopKReference",
    "IndependentIAETopKResult",
    "InternalCLUCBStyleSelector",
    "IterativeAEThresholdScan",
    "LETTER_SPEC",
    "LemmaCheck",
    "LowerBoundBlock",
    "LowerBoundProgramRecord",
    "LoadedUCIDataset",
    "MeasuredBoundaryBracket",
    "NaturalArmDistribution",
    "NaturalPurificationStatevectorOracle",
    "OfflineReplayBackend",
    "OPTDIGITS_SPEC",
    "OracleModel",
    "OrientationSeparationRecord",
    "PhaseQubitCandidate",
    "ProofLedger",
    "ProofLedgerEntry",
    "PreregisteredFixture",
    "QGapSelect",
    "QGapSelectPortfolioAdapter",
    "QuantumBenchmarkConfig",
    "QuantumBenchmarkRunner",
    "QBoundaryEstimator",
    "QGAPSELECT_INFORMATION_REGIME",
    "QGapFlag",
    "QueryKind",
    "QueryBudget",
    "QueryLedger",
    "RandomSelector",
    "ResearchGap",
    "ResearchGapAudit",
    "Seed",
    "SemanticVariant",
    "SelectorBenchmarkAggregate",
    "SelectorBenchmarkRun",
    "SelectorBudget",
    "SelectorLandscape",
    "SourceOracleBudget",
    "StoppingProfile",
    "StoppingResources",
    "StoppingResult",
    "StoppingSummary",
    "StoppingUnitaryLemmaScaffold",
    "StrictTopKHistoryCertificate",
    "SuccessiveHalvingSelector",
    "Task",
    "TheoremObligation",
    "TopKInstance",
    "ToyActivityHistoryTransducer",
    "UnknownBoundaryHistoryRecord",
    "UniformTopKSelector",
    "UnifiedHardFamily",
    "UnifiedQueryInterface",
    "UnifiedTheoremClosureAudit",
    "UCIClassifierBenchmark",
    "ValidatorResult",
    "VariableTimeChargedHistoryRecord",
    "VariableTimeChargedLevel",
    "VariableTimeCoherentActivityHistoryCore",
    "VariableTimeCoherentHistoryResult",
    "VariableTimeHistoryConfig",
    "VariableTimeStoppingTransducer",
    "aggregate_attack_metrics",
    "aggregate_benchmark_records",
    "aggregate_ccfa_matched_trials",
    "analyze_frozen_quantum_reference_pairs",
    "analyze_paired_fixtures",
    "build_research_gap_audit",
    "build_proof_ledger",
    "build_uci_classifier_benchmark",
    "build_unified_theorem_closure_audit",
    "build_stopping_unitary_lemma_scaffold",
    "build_frozen_empirical_coherent_oracle",
    "collect_local_records",
    "composition_audit_sweep",
    "composition_frontier_loglog_slope",
    "composition_frontier_record",
    "composition_frontier_sweep",
    "composition_loglog_slope",
    "deterministic_boundary_phases",
    "descriptive_loglog_slope",
    "full_workspace_rank_one_diffusion",
    "generate_bernoulli_landscape",
    "generate_exact_count_fixture",
    "generate_frozen_quantum_instance_design",
    "holm_fwer_adjusted_p_values",
    "logarithmic_precision_schedule",
    "load_covertype",
    "load_letter_recognition",
    "load_optdigits",
    "load_sklearn_digits_offline",
    "lower_bound_program_loglog_slope",
    "lower_bound_program_record",
    "lower_bound_program_sweep",
    "make_benchmark_instance",
    "machine_readable_status_map",
    "matched_campaign_manifest_hash",
    "orientation_separation_record",
    "orientation_separation_sweep",
    "orientation_family_composition_record",
    "one_sided_clopper_pearson_lower",
    "unknown_boundary_history_loglog_slope",
    "unknown_boundary_history_record",
    "unknown_boundary_history_sweep",
    "paired_counterfactual_event",
    "precision_bits_for_epsilon",
    "precision_bits_from_history_record",
    "proof_ledger_markdown",
    "qbatch_extract",
    "qboundary",
    "qgap_flag",
    "paired_query_ratios",
    "research_gap_markdown",
    "run_diffusion_ablation",
    "run_coherent_activity_history_statevector",
    "run_frozen_selector_benchmark",
    "run_frozen_quantum_reference_benchmark",
    "run_independent_iae_topk",
    "run_phase_grid_sweep",
    "run_qpe_acceptance_sweep",
    "run_unitary_validation",
    "run_variable_time_coherent_activity_history",
    "run_verifier_calibration",
    "select_hardness_quantile_anchors",
    "run_attack_study",
    "summarize_charged_activity",
    "summarize_composition_frontier",
    "summarize_lower_bound_program",
    "summarize_proof_ledger",
    "summarize_quantum_benchmark",
    "summarize_stopping_transducer",
    "summarize_stopping_unitary_theorem",
    "summarize_unknown_boundary_grid",
    "summarize_variable_time_charged",
    "summarize_fixed_fixture_calibration",
    "stopping_unitary_lemma_markdown",
    "toy_transducer_from_history_record",
    "variable_time_charged_history_loglog_slope",
    "variable_time_charged_history_record",
    "variable_time_charged_history_sweep",
    "evaluate_ccfa_evidence_gate",
    "iter_ccfa_matched_trials",
    "validate_complete_matched_panel",
    "AtomicQueryCapOracle",
    "GCGSGreedyGraphSelector",
]

__version__ = "0.1.0"
