"""Variable-time stopping transducer skeleton.

This module is the executable bridge between the charged finite-phase
classifier and the desired P0-U08 circuit theorem.  It builds a reversible
relation oracle whose registers are ``(index, stop_level, active, output)``:

* finite-QPE predicates are generated by :class:`ChargedPhaseHistoryTransducer`;
* every arm receives a first-output stopping code, or a sentinel if unresolved;
* compute XORs the stopping code and flags into work registers;
* phase uses compute--phase--uncompute and leaves no flag garbage; and
* the resource summary records serial full-history cost and variable-time RMS
  stopping-cost proxies.

It is still a skeleton, not a theorem.  The boundary is supplied as a phase
window and the variable-time costs are auditable ledgers, not a proven upper
bound.
"""

from __future__ import annotations

import math
import operator
from collections import Counter
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from types import MappingProxyType

import numpy as np
from numpy.typing import NDArray

from .charged_activity_history import (
    ChargedPhaseHistoryTransducer,
    FinitePhaseClassification,
)
from .unknown_boundary_history import UnknownBoundaryHistoryRecord
from .variable_time_charged_history import precision_bits_for_epsilon

ComplexState = NDArray[np.complex128]
BACKEND = "numpy_exact_statevector_variable_time_stopping_skeleton"
CLAIM_STATUS = "variable_time_stopping_transducer_skeleton_no_theorem"


def _integer(value: object, name: str) -> int:
    if isinstance(value, bool):
        raise TypeError(f"{name} must be an integer, not bool")
    try:
        return int(operator.index(value))
    except TypeError as error:
        raise TypeError(f"{name} must be an integer") from error


def _next_power_of_two(value: int) -> int:
    if value < 1:
        raise ValueError("value must be positive")
    return 1 << (value - 1).bit_length()


def _as_unique_indices(values: Sequence[int], *, upper: int, name: str) -> tuple[int, ...]:
    try:
        indices = tuple(_integer(value, f"{name} index") for value in values)
    except TypeError as error:
        raise TypeError(f"{name} must be a sequence of integers") from error
    if len(set(indices)) != len(indices):
        raise ValueError(f"{name} indices must be unique")
    if any(not 0 <= index < upper for index in indices):
        raise IndexError(f"{name} contains an index outside [0, {upper})")
    return indices


@dataclass(frozen=True, slots=True)
class StoppingProfile:
    """One arm's charged stopping profile."""

    index: int
    true_phase: float
    first_active_level: int | None
    first_output_level: int | None
    stop_code: int
    ever_active: bool
    output: bool
    stopping_cost: int
    serial_full_history_cost: int
    classifications: tuple[FinitePhaseClassification, ...]


@dataclass(frozen=True, slots=True)
class StoppingSummary:
    """Aggregate variable-time stopping resource summary."""

    n_arms: int
    level_count: int
    output_count: int
    active_count: int
    unresolved_count: int
    serial_full_history_cost_per_branch: int
    mean_stopping_cost: float
    coherent_branch_rms_cost: float
    all_branch_rms_search_proxy: float
    max_stopping_cost: int
    variable_over_serial_per_branch: float
    output_fraction: float
    active_fraction: float
    stop_code_sentinel: int
    predicate_source: str = "charged_finite_qpe_first_output_stopping"


@dataclass(frozen=True, slots=True)
class StoppingResources:
    """Logical resources for the stopping-time relation skeleton."""

    query_counts: Mapping[str, int]
    n_arms: int
    level_count: int
    precision_bits_by_level: tuple[int, ...]
    index_dimension: int
    stop_dimension: int
    statevector_dimension: int
    summary: StoppingSummary
    backend: str = BACKEND
    claim_status: str = CLAIM_STATUS


@dataclass(frozen=True, slots=True)
class StoppingResult:
    """State and diagnostics after a stopping transducer operation."""

    state: ComplexState
    resources: StoppingResources
    active_probability: float
    output_probability: float


class VariableTimeStoppingTransducer:
    """Exact-state stopping relation generated from charged finite-QPE flags."""

    def __init__(
        self,
        arm_phases: Sequence[float],
        precision_bits_by_level: Sequence[int],
        *,
        boundary_phase: float = 0.5,
        activity_window_multipliers: Sequence[float] | None = None,
        guard_band: float = 0.0,
    ) -> None:
        self.phase_transducer = ChargedPhaseHistoryTransducer(
            arm_phases,
            precision_bits_by_level,
            boundary_phase=boundary_phase,
            activity_window_multipliers=activity_window_multipliers,
            guard_band=guard_band,
        )
        self.arm_phases = self.phase_transducer.arm_phases
        self.precision_bits_by_level = self.phase_transducer.precision_bits_by_level
        self.qpe_query_units_by_level = self.phase_transducer.qpe_query_units_by_level
        self.n_arms = self.phase_transducer.n_arms
        self.level_count = self.phase_transducer.level_count
        self.stop_code_sentinel = self.level_count
        self.index_dimension = _next_power_of_two(self.n_arms)
        self.stop_dimension = _next_power_of_two(self.level_count + 1)
        self._ledger: Counter[str] = Counter()
        self._profiles = tuple(self._build_profile(index) for index in range(self.n_arms))
        self._summary = self._build_summary()

    @property
    def shape(self) -> tuple[int, int, int, int]:
        return (self.index_dimension, self.stop_dimension, 2, 2)

    @property
    def statevector_dimension(self) -> int:
        return int(np.prod(self.shape))

    def zero_state(self) -> ComplexState:
        state = np.zeros(self.statevector_dimension, dtype=np.complex128)
        state[0] = 1.0
        return state

    def uniform_index_state(self, *, indices: Sequence[int] | None = None) -> ComplexState:
        selected_indices = tuple(range(self.n_arms)) if indices is None else tuple(indices)
        if not selected_indices:
            raise ValueError("indices cannot be empty")
        indices_checked = _as_unique_indices(
            selected_indices, upper=self.n_arms, name="indices"
        )
        view = np.zeros(self.shape, dtype=np.complex128)
        amplitude = 1.0 / math.sqrt(len(indices_checked))
        view[indices_checked, 0, 0, 0] = amplitude
        return view.reshape(-1)

    def query_snapshot(self) -> Mapping[str, int]:
        return MappingProxyType(dict(self._ledger))

    def resource_snapshot(self) -> StoppingResources:
        return StoppingResources(
            query_counts=self.query_snapshot(),
            n_arms=self.n_arms,
            level_count=self.level_count,
            precision_bits_by_level=self.precision_bits_by_level,
            index_dimension=self.index_dimension,
            stop_dimension=self.stop_dimension,
            statevector_dimension=self.statevector_dimension,
            summary=self.summary(),
        )

    def profile(self, index: int) -> StoppingProfile:
        index = _integer(index, "index")
        if not 0 <= index < self.n_arms:
            raise IndexError("index is outside the valid arms")
        return self._profiles[index]

    def profiles(self) -> tuple[StoppingProfile, ...]:
        return self._profiles

    def summary(self) -> StoppingSummary:
        return self._summary

    def _build_profile(self, index: int) -> StoppingProfile:
        classifications = tuple(
            self.phase_transducer.classify(level, index)
            for level in range(self.level_count)
        )
        active_levels = tuple(item.level for item in classifications if item.active)
        output_levels = tuple(item.level for item in classifications if item.output)
        first_active = active_levels[0] if active_levels else None
        first_output = output_levels[0] if output_levels else None
        stop_code = first_output if first_output is not None else self.stop_code_sentinel
        serial_cost = int(sum(self.qpe_query_units_by_level))
        if first_output is None:
            stopping_cost = serial_cost
        else:
            stopping_cost = int(sum(self.qpe_query_units_by_level[: first_output + 1]))
        return StoppingProfile(
            index=index,
            true_phase=self.arm_phases[index],
            first_active_level=first_active,
            first_output_level=first_output,
            stop_code=stop_code,
            ever_active=bool(active_levels),
            output=first_output is not None,
            stopping_cost=stopping_cost,
            serial_full_history_cost=serial_cost,
            classifications=classifications,
        )

    def _build_summary(self) -> StoppingSummary:
        costs = np.asarray([profile.stopping_cost for profile in self._profiles])
        serial = int(sum(self.qpe_query_units_by_level))
        output_count = sum(profile.output for profile in self._profiles)
        active_count = sum(profile.ever_active for profile in self._profiles)
        branch_rms = float(np.sqrt(np.mean(costs.astype(np.float64) ** 2)))
        all_branch_rms = float(np.sqrt(np.sum(costs.astype(np.float64) ** 2)))
        return StoppingSummary(
            n_arms=self.n_arms,
            level_count=self.level_count,
            output_count=int(output_count),
            active_count=int(active_count),
            unresolved_count=int(self.n_arms - output_count),
            serial_full_history_cost_per_branch=serial,
            mean_stopping_cost=float(np.mean(costs)),
            coherent_branch_rms_cost=branch_rms,
            all_branch_rms_search_proxy=all_branch_rms,
            max_stopping_cost=int(np.max(costs)),
            variable_over_serial_per_branch=branch_rms / serial if serial else 0.0,
            output_fraction=output_count / self.n_arms,
            active_fraction=active_count / self.n_arms,
            stop_code_sentinel=self.stop_code_sentinel,
        )

    def _view(self, state: ComplexState) -> ComplexState:
        values = np.asarray(state, dtype=np.complex128)
        if values.ndim != 1 or values.size != self.statevector_dimension:
            raise ValueError(
                "expected a flat statevector of length "
                f"{self.statevector_dimension}, got {values.shape}"
            )
        if not np.isclose(np.linalg.norm(values), 1.0, atol=1e-10):
            raise ValueError("statevector must be normalized")
        return values.copy().reshape(self.shape)

    def _charge_compute(self, tag: str) -> None:
        summary = self.summary()
        self._ledger[f"{tag}:compute"] += 1
        self._ledger["stopping:serial_full_history_cost_per_branch"] += (
            summary.serial_full_history_cost_per_branch
        )
        self._ledger["stopping:ceil_branch_rms_cost"] += int(
            math.ceil(summary.coherent_branch_rms_cost)
        )
        self._ledger["stopping:ceil_all_branch_rms_search_proxy"] += int(
            math.ceil(summary.all_branch_rms_search_proxy)
        )

    def apply_compute(
        self,
        state: ComplexState,
        *,
        tag: str = "stopping_history",
    ) -> ComplexState:
        view = self._view(state)
        for index, profile in enumerate(self._profiles):
            block = view[index].copy()
            for stop_register in range(self.stop_dimension):
                for active_flag in range(2):
                    for output_flag in range(2):
                        new_stop = stop_register ^ profile.stop_code
                        new_active = active_flag ^ int(profile.ever_active)
                        new_output = output_flag ^ int(profile.output)
                        view[index, new_stop, new_active, new_output] = block[
                            stop_register, active_flag, output_flag
                        ]
        self._charge_compute(tag)
        return view.reshape(-1)

    def apply_phase(
        self,
        state: ComplexState,
        *,
        phase_on: str = "output",
        tag: str = "stopping_history",
    ) -> StoppingResult:
        if phase_on not in {"active", "output", "active_output"}:
            raise ValueError("phase_on must be active, output, or active_output")
        computed = self.apply_compute(state, tag=tag)
        view = self._view(computed)
        active_probability = float(np.sum(np.abs(view[:, :, 1, :]) ** 2))
        output_probability = float(np.sum(np.abs(view[:, :, :, 1]) ** 2))
        if phase_on == "active":
            view[:, :, 1, :] *= -1.0
        elif phase_on == "output":
            view[:, :, :, 1] *= -1.0
        else:
            view[:, :, 1, 1] *= -1.0
        self._ledger[f"{tag}:phase:{phase_on}"] += 1
        restored = self.apply_compute(view.reshape(-1), tag=tag)
        return StoppingResult(
            state=restored,
            resources=self.resource_snapshot(),
            active_probability=active_probability,
            output_probability=output_probability,
        )


def precision_bits_from_history_record(
    record: UnknownBoundaryHistoryRecord,
    *,
    precision_multiplier: float = 2.0,
    min_precision_bits: int = 1,
    max_precision_bits: int | None = None,
) -> tuple[int, ...]:
    """Return finite-QPE precision bits aligned with a history record."""

    if not isinstance(record, UnknownBoundaryHistoryRecord):
        raise TypeError("record must be an UnknownBoundaryHistoryRecord")
    return tuple(
        precision_bits_for_epsilon(
            layer.epsilon,
            precision_multiplier=precision_multiplier,
            min_precision_bits=min_precision_bits,
            max_precision_bits=max_precision_bits,
        )
        for layer in record.layers
    )
